import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { ProductKitSettings, JigsawV3Settings } from '../types/jigsawV3';

/**
 * Module F: Product Kit Export
 * Exports a complete product bundle as ZIP
 */

export interface KitExportData {
  cutSvg: string;
  fullSvg: string;
  engravingPng?: string;
  mockupPng?: string;
  settings: JigsawV3Settings;
}

/**
 * Export product kit as ZIP
 */
export async function exportProductKit(
  data: KitExportData,
  settings: ProductKitSettings,
  filename: string
): Promise<void> {
  const zip = new JSZip();
  const timestamp = new Date().toISOString().slice(0, 10);
  const baseName = filename.replace('.svg', '');

  // Add cut SVG (always included)
  if (settings.includeCutSvg) {
    zip.file(`${baseName}_cut.svg`, data.cutSvg);
  }

  // Add full SVG
  if (settings.includeFullSvg) {
    zip.file(`${baseName}_full.svg`, data.fullSvg);
  }

  // Add engraving PNG
  if (settings.includeEngravingPng && data.engravingPng) {
    const pngData = data.engravingPng.split(',')[1]; // Remove data:image/png;base64,
    zip.file(`${baseName}_engraving_318dpi.png`, pngData, { base64: true });
  }

  // Add mockup PNG
  if (settings.includeMockupPng && data.mockupPng) {
    const pngData = data.mockupPng.split(',')[1];
    zip.file(`${baseName}_mockup.png`, pngData, { base64: true });
  }

  // Add settings JSON
  if (settings.includeSettingsJson) {
    const settingsJson = JSON.stringify(data.settings, null, 2);
    zip.file('settings.json', settingsJson);
  }

  // Add README
  if (settings.includeReadme) {
    const readme = generateReadme(data.settings);
    zip.file('README.txt', readme);
  }

  // Generate and download ZIP
  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${baseName}_kit_${timestamp}.zip`);
}

/**
 * Generate README content
 */
function generateReadme(settings: JigsawV3Settings): string {
  const { widthMm, heightMm, rows, columns } = settings;
  const pieceCount = rows * columns;

  return `JIGSAW PUZZLE - LASER CUTTING KIT
Generated by LaserFilesPro Studio V3
Date: ${new Date().toISOString().slice(0, 10)}

========================================
PUZZLE SPECIFICATIONS
========================================
Dimensions: ${widthMm}mm × ${heightMm}mm
Grid: ${rows} rows × ${columns} columns
Total Pieces: ${pieceCount}
Knob Style: ${settings.knobStyle}
${settings.difficulty ? `Difficulty Level: ${settings.difficulty.level}/10` : ''}

========================================
FILES INCLUDED
========================================
- *_cut.svg: Cut paths only (CUT_PIECES + CUT_BACKING + CUT_POCKET_FRAME)
- *_full.svg: Complete file with all layers (CUT + ENGRAVE)
${settings.photoEngraving?.enabled ? '- *_engraving_318dpi.png: Engraving image at 318 DPI\n' : ''}
${settings.productKit?.includeMockupPng ? '- *_mockup.png: Preview mockup\n' : ''}
- settings.json: Complete settings for reproduction

========================================
MATERIAL RECOMMENDATIONS
========================================
Recommended Materials:
- 3mm Plywood (Baltic Birch)
- 3mm MDF
- 3mm Acrylic

Kerf Compensation: ${settings.kerfOffset}mm
Fit Mode: ${settings.fitMode}

========================================
LIGHTBURN IMPORT INSTRUCTIONS
========================================
1. Open LightBurn
2. Import *_cut.svg
3. Set layer colors:
   - Red (#FF0000) → CUT_PIECES (Cut layer)
   - Blue (#0000FF) → CUT_BACKING/CUT_POCKET_FRAME (Cut layer)
   - Black (#000000) → ENGRAVE layers (Engrave layer)

4. Recommended Settings:
   Cut: Speed 10mm/s, Power 100%, Pass 1
   Engrave: Speed 300mm/s, Power 20%, DPI 318

5. If using engraving PNG:
   - Import *_engraving_318dpi.png
   - Set to Image mode, 318 DPI
   - Align to puzzle bounds

========================================
ASSEMBLY TIPS
========================================
${settings.pocketFrame?.enabled ? `
- Pocket Frame Included
- Frame Margin: ${settings.pocketFrame.pocketMarginMm}mm
- Wall Thickness: ${settings.pocketFrame.wallThicknessMm}mm
- Assemble puzzle first, then place in pocket frame
` : '- No frame included - puzzle pieces only'}

${settings.pieceNumbering ? '- Piece IDs engraved on back (A1, A2, B1, B2...)\n' : ''}
${settings.backingBoard?.enabled ? '- Backing board included for stability\n' : ''}

========================================
NOTES
========================================
- All dimensions in millimeters (mm)
- Stroke width: 0.001mm (hairline)
- Paths are closed and laser-safe
- Random seed: ${settings.randomSeed} (for reproduction)

For support: https://laserfilespro.com/support
`;
}

/**
 * Generate mockup preview image
 */
export async function generateMockupPreview(
  svgContent: string,
  width: number,
  height: number
): Promise<string> {
  return new Promise((resolve) => {
    const canvas = document.createElement('canvas');
    const scale = 2; // 2x for better quality
    canvas.width = width * scale;
    canvas.height = height * scale;
    const ctx = canvas.getContext('2d');

    if (!ctx) {
      resolve('');
      return;
    }

    // White background
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Create SVG blob and image
    const svgBlob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);
    const img = new Image();

    img.onload = () => {
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      
      // Add subtle shadow effect
      ctx.shadowColor = 'rgba(0, 0, 0, 0.1)';
      ctx.shadowBlur = 10 * scale;
      ctx.shadowOffsetX = 5 * scale;
      ctx.shadowOffsetY = 5 * scale;

      const dataUrl = canvas.toDataURL('image/png');
      URL.revokeObjectURL(url);
      resolve(dataUrl);
    };

    img.onerror = () => {
      URL.revokeObjectURL(url);
      resolve('');
    };

    img.src = url;
  });
}

/**
 * Validate kit export settings
 */
export function validateKitExportSettings(settings: ProductKitSettings): string[] {
  const warnings: string[] = [];

  if (!settings.includeCutSvg && !settings.includeFullSvg) {
    warnings.push('At least one SVG file should be included');
  }

  if (settings.includeEngravingPng && !settings.includeFullSvg) {
    warnings.push('Full SVG recommended when including engraving PNG');
  }

  return warnings;
}
