import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Help & Documentation – LaserFilesPro Studio',
  description: 'Learn how to use LaserFilesPro Studio tools for laser cutting design and production.',
};

export default function StudioHelpPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-8 px-4 py-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-slate-100">
          Help & Documentation
        </h1>
        <p className="mt-2 text-lg text-slate-400">
          Everything you need to know about LaserFilesPro Studio
        </p>
      </div>

      {/* What is LaserFilesPro Studio */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          What is LaserFilesPro Studio?
        </h2>
        <p className="text-slate-300">
          LaserFilesPro Studio is an all-in-one web-based platform for laser cutting design and production. 
          Create laser-ready SVG files for boxes, signs, labels, jigs, and more—all in your browser, no software installation required.
        </p>
        <p className="text-slate-300">
          Our tools are designed for makers, small businesses, and production shops who need reliable, 
          professional-quality designs without the complexity of traditional CAD software.
        </p>
      </section>

      {/* Compatible Software */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          Compatible Software
        </h2>
        <p className="text-slate-300">
          All SVG files generated by LaserFilesPro Studio are compatible with popular laser cutting software:
        </p>
        <ul className="ml-6 list-disc space-y-2 text-slate-300">
          <li>
            <strong className="text-slate-200">LightBurn</strong> – Industry-standard laser software (recommended)
          </li>
          <li>
            <strong className="text-slate-200">RDWorks</strong> – Common with Chinese CO2 lasers
          </li>
          <li>
            <strong className="text-slate-200">LaserGRBL</strong> – Free, open-source GRBL controller
          </li>
          <li>
            <strong className="text-slate-200">K40 Whisperer</strong> – For K40 laser cutters
          </li>
          <li>
            <strong className="text-slate-200">Inkscape</strong> – Free vector graphics editor
          </li>
          <li>
            <strong className="text-slate-200">Adobe Illustrator</strong> – Professional vector design
          </li>
        </ul>
        <div className="rounded-lg border border-blue-800 bg-blue-950/20 p-4">
          <p className="text-sm text-blue-200">
            <strong>💡 Tip:</strong> We recommend LightBurn for the best experience. 
            It handles our SVG files perfectly and offers excellent laser control.
          </p>
        </div>
      </section>

      {/* General Tips */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          General Tips for Laser Cutting
        </h2>
        
        <div className="space-y-6">
          <div>
            <h3 className="text-lg font-semibold text-slate-200">Understanding Kerf</h3>
            <p className="mt-2 text-slate-300">
              <strong>Kerf</strong> is the width of material removed by the laser beam. 
              Typical kerf values:
            </p>
            <ul className="ml-6 mt-2 list-disc space-y-1 text-slate-300">
              <li>3mm plywood (CO2 laser): ~0.15mm</li>
              <li>4mm plywood (CO2 laser): ~0.18mm</li>
              <li>3mm acrylic: ~0.20mm</li>
              <li>Metal (fiber laser): ~0.05-0.10mm</li>
            </ul>
            <p className="mt-2 text-slate-300">
              Always test cut a small piece to measure your actual kerf before production runs.
            </p>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-slate-200">Test Cuts Are Essential</h3>
            <p className="mt-2 text-slate-300">
              Before cutting expensive materials or large batches:
            </p>
            <ul className="ml-6 mt-2 list-disc space-y-1 text-slate-300">
              <li>Cut a small test piece with the same material</li>
              <li>Verify dimensions match your design</li>
              <li>Check that parts fit together (for boxes, jigs, etc.)</li>
              <li>Adjust your design if needed</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-slate-200">Material Recommendations</h3>
            <ul className="ml-6 mt-2 list-disc space-y-1 text-slate-300">
              <li><strong>Plywood:</strong> 3-6mm for boxes, signs, jigs</li>
              <li><strong>MDF:</strong> 3-6mm for jigs, templates (cheap, stable)</li>
              <li><strong>Acrylic:</strong> 3-5mm for signs, labels, badges</li>
              <li><strong>Cardstock:</strong> Laser-safe cardstock for temporary items</li>
              <li><strong>Bamboo:</strong> 3mm for eco-friendly products</li>
            </ul>
          </div>

          <div>
            <h3 className="text-lg font-semibold text-slate-200">Engraving vs Cutting</h3>
            <p className="mt-2 text-slate-300">
              Our tools generate two types of paths:
            </p>
            <ul className="ml-6 mt-2 list-disc space-y-1 text-slate-300">
              <li>
                <strong>Cutting paths:</strong> Solid lines that cut through material 
                (high power, slow speed)
              </li>
              <li>
                <strong>Engraving paths:</strong> Text and details that mark the surface 
                (medium power, fast speed)
              </li>
            </ul>
            <p className="mt-2 text-slate-300">
              In LightBurn, assign different layers to cutting and engraving for optimal results.
            </p>
          </div>
        </div>
      </section>

      {/* Tool Categories */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          Tool Categories
        </h2>
        
        <div className="space-y-4">
          <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
            <h3 className="font-semibold text-slate-200">Boxes & Structures</h3>
            <p className="mt-1 text-sm text-slate-400">
              Create parametric boxes with finger joints, hinges, and sliding drawers.
            </p>
          </div>

          <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
            <h3 className="font-semibold text-slate-200">Layout & Production</h3>
            <p className="mt-1 text-sm text-slate-400">
              Tools for batch production: panel splitting, ornament layouts, jigs, and bulk name tags.
            </p>
          </div>

          <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
            <h3 className="font-semibold text-slate-200">Personalization</h3>
            <p className="mt-1 text-sm text-slate-400">
              Create custom signs, keychains, coasters, badges, and product labels with engraved text.
            </p>
          </div>

          <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
            <h3 className="font-semibold text-slate-200">Utilities</h3>
            <p className="mt-1 text-sm text-slate-400">
              Specialized tools: image engraving prep and inlay offset calculator for marquetry.
            </p>
          </div>
        </div>
      </section>

      {/* Getting Started */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          Getting Started
        </h2>
        <ol className="ml-6 list-decimal space-y-3 text-slate-300">
          <li>
            <strong className="text-slate-200">Choose a tool</strong> from the{' '}
            <a href="/studio/tools" className="text-sky-400 hover:text-sky-300">
              Tools page
            </a>
          </li>
          <li>
            <strong className="text-slate-200">Configure your design</strong> using the input controls
          </li>
          <li>
            <strong className="text-slate-200">Preview</strong> your design in real-time
          </li>
          <li>
            <strong className="text-slate-200">Export SVG</strong> when ready
          </li>
          <li>
            <strong className="text-slate-200">Import to laser software</strong> (LightBurn recommended)
          </li>
          <li>
            <strong className="text-slate-200">Test cut</strong> on scrap material first
          </li>
          <li>
            <strong className="text-slate-200">Production cut</strong> with confidence!
          </li>
        </ol>
      </section>

      {/* Support */}
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold text-slate-100">
          Need More Help?
        </h2>
        <p className="text-slate-300">
          Each tool has built-in help content with specific tips and recommendations. 
          Click the <strong>Help</strong> button in any tool to access detailed guidance.
        </p>
        <div className="rounded-lg border border-slate-800 bg-slate-900/40 p-4">
          <p className="text-sm text-slate-300">
            For additional support, visit our community forums or contact us through the website.
          </p>
        </div>
      </section>
    </div>
  );
}
