/**
 * Auto-generated list of available fonts in keychain folder
 * This file should be regenerated when fonts are added/removed
 */

export const AVAILABLE_FONTS = [
  "Absolute.ttf",
  "Agatha.ttf",
  "Almonde.ttf",
  "Amastay.ttf",
  "Amelissa Partis.ttf",
  "Angelin Calligraphy 2.ttf",
  "Angelina Bold Italic.ttf",
  "Angelina Bold.ttf",
  "Angelina Italic.ttf",
  "Angelina Outline Italic.ttf",
  "Angelina Outline.ttf",
  "Angelina Vintage.ttf",
  "Arsegtosia Script 1.ttf",
  "Ashley Marie.ttf",
  "Astoria.ttf",
  "Atarford.ttf",
  "Baby Barbie.ttf",
  "Baby Boho.ttf",
  "Babybohoscript.ttf",
  "Babyish Script.ttf",
  "Background.ttf",
  "Barbie Script.ttf",
  "Barbie Simple Script.ttf",
  "Basketball 1.ttf",
  "Basthiyan Script.ttf",
  "Berttingka.ttf",
  "Biblings.ttf",
  "Birthday.ttf",
  "Black Sample.ttf",
  "Black Vintage Script 1.ttf",
  "Blosky Script.ttf",
  "Blueberry.ttf",
  "Boho.ttf",
  "Bosnia Script.ttf",
  "Bosthany Signature.ttf",
  "Bristol Extrude.ttf",
  "Bristol Script.ttf",
  "Calestine.ttf",
  "Charistina Script.ttf",
  "Chifa Script.ttf",
  "Chimon Italic.ttf",
  "Chimon Signature.ttf",
  "Chimon.ttf",
  "Chocolate Banana Outline.ttf",
  "Chocolate Banana.ttf",
  "Chocolates.ttf",
  "Chryselles Script.ttf",
  "Cupcake Squishy.ttf",
  "Daustley.ttf",
  "Delighter.ttf",
  "Easirable.ttf",
  "Entire Spring.ttf",
  "Family Script.ttf",
  "Ferlistan.ttf",
  "Flonday Script Variable.ttf",
  "Flondayscript Black.ttf",
  "Flondayscript Bold.ttf",
  "Flondayscript Extrabold.ttf",
  "Flondayscript Extralight.ttf",
  "Flondayscript Light.ttf",
  "Flondayscript Medium.ttf",
  "Flondayscript Regular.ttf",
  "Flondayscript Semibold.ttf",
  "Flondayscript Thin.ttf",
  "Glasthone Calligraphy Font.ttf",
  "Handmode.ttf",
  "Handwriting.ttf",
  "Hasterline.ttf",
  "Heart Style.ttf",
  "Heartbeat.ttf",
  "Heather.ttf",
  "Hello Barbie.ttf",
  "Hello Mother 1.ttf",
  "Hey Girl.ttf",
  "Hillmont.ttf",
  "Hopeless.ttf",
  "Italian Delight.ttf",
  "Kaelyna.ttf",
  "Kartyna.ttf",
  "Kingdom.ttf",
  "Letters To Elise.ttf",
  "Liskiya Seholly Script.ttf",
  "Lovely Spider.ttf",
  "Lustia Script.ttf",
  "Maddison.ttf",
  "Marselo Italic.ttf",
  "Marselo.ttf",
  "Master Script.ttf",
  "Masterline Script.ttf",
  "Melon Script 2.ttf",
  "Milkshake.ttf",
  "Mother Father Script.ttf",
  "My Love Sans.ttf",
  "My Love Script.ttf",
  "Otter Garden.ttf",
  "Overthinker.ttf",
  "Pinkgirls.ttf",
  "Qallisa Italic.ttf",
  "Qallisa.ttf",
  "Rena Extrude.ttf",
  "Rena Script.ttf",
  "Samantha Script.ttf",
  "Santiago.ttf",
  "Saturday.ttf",
  "Selfino Script.ttf",
  "September Script.ttf",
  "September.ttf",
  "Shabby.ttf",
  "Shella Extrude.ttf",
  "Shella Script.ttf",
  "Shenapan.ttf",
  "Shenthany Runway.ttf",
  "Sholyscript.ttf",
  "Simple Signature.ttf",
  "Splashed.ttf",
  "Starford.ttf",
  "Straight.ttf",
  "Struggle.ttf",
  "Stylish Calligraphy.ttf",
  "Sulastri Script.ttf",
  "Swatch Out.ttf",
  "Sweet Bestie Script.ttf",
  "Sweet Honey.ttf",
  "The Family Calligraphy Script 1.ttf",
  "Welcome.ttf",
  "Wonderful Holiday.ttf"
];
